CiscoDevNet/ansible-aci

- plugins/modules/aci_cloud_cidr.py
- tests/integration/targets/aci_cloud_cidr/aliases
- tests/integration/targets/aci_cloud_cidr/tasks/main.yml
- update doc and parameters of 'aci_cloud_cidr' module
- build test file for this module
> Aci cloud cidr module

- plugins/modules/aci_l3out_extepg_to_contract.py
- tests/integration/targets/aci_l3out_extepg_to_contract/aliases
- tests/integration/targets/aci_l3out_extepg_to_contract/tasks/main.yml
Changes made to docs and minor modifications in the module.
Test file for the module.
> Review and modification: aci_l3out_extepg_to_contract

- plugins/modules/aci_cloud_region.py
- tests/integration/targets/aci_cloud_region/aliases
- tests/integration/targets/aci_cloud_region/tasks/main.yml
- complete aci_cloud_region module which is used to query regions
- build test file for this module
> aci_cloud_region module

- plugins/modules/aci_l2out_extepg.py
- tests/integration/targets/aci_l2out_extepg/aliases
- tests/integration/targets/aci_l2out_extepg/tasks/main.yml
Added new module aci_l2out_extepg and its test file
> New module l2out_extepg

- plugins/modules/aci_interface_policy_link_level.py
- tests/integration/targets/aci_interface_policy_link_level/aliases
- tests/integration/targets/aci_interface_policy_link_level/tasks/main.yml
1. Changes made to test file of Link Level Policy
Resolves #12 
Resolves ansible/ansible#62138
> Changes to Link Level Policy

- plugins/modules/aci_bd_dhcp_label.py
- tests/integration/targets/aci_bd_dhcp_label/aliases
- tests/integration/targets/aci_bd_dhcp_label/tasks/main.yml
Test file included.
Resolves ansible/ansible#64446
Resolves ansible/ansible#32571
Resolves #15
> Add module and test file for aci_bd_dhcp_label

- plugins/modules/aci_access_port_block_to_access_port.py
- plugins/modules/aci_access_port_to_interface_policy_leaf_profile.py
- plugins/modules/aci_interface_policy_leaf_profile.py
- tests/integration/targets/aci_access_port_block_to_access_port/tasks/main.yml
- tests/integration/targets/aci_access_port_to_interface_policy_leaf_profile/tasks/main.yml
- tests/integration/targets/aci_interface_policy_leaf_profile/tasks/main.yml
Fex for : 
1. Leaf Interface profile: aci_interface_policy_leaf_profile
2. Access port: aci_access_port_to_interface_policy_leaf_profile
3. Port block: aci_access_port_block_to_access_port
Resolves #17 
Resolves ansible/ansible#53394
> Added Fex capability to three modules

- plugins/module_utils/aci.py
- plugins/modules/aci_firmware_source.py
- tests/integration/targets/aci_firmware_source/tasks/main.yml
- fix the issue where firmware_source module doesn't report change correctly.
- make some changes to test file to improve coverage rate.
resolve #24
> [aci_firmware_source] fix issue of 'current' in firmware_source module

- plugins/modules/aci_aep.py
- tests/integration/targets/aci_aep/tasks/main.yml
Fixes idempotency issue when disabling infra_vlan
Added test file
> [aci_aep] Enable/Disable infra vlan in aci_aep fixes #44

- plugins/modules/aci_rest.py
Ability to dump configuration to output file
> [aci_rest] Addition of dump config fixes #42

- plugins/modules/aci_rest.py
- tests/integration/targets/aci_rest/tasks/main.yml
- tests/integration/targets/aci_rest/tasks/xml_string.yml
- support YAML content with XML paths by converting the YAML to XML payload
- implement test file for XML path
resolve #31
> [aci_rest]  support YAML content with XML path

- plugins/modules/aci_epg_to_domain.py
- tests/integration/targets/aci_epg_to_domain/tasks/main.yml
Addition of promiscuous mode for vmm domain association.
Updated test file.
> [aci_epg_to_domain] addition of promiscuous mode fixes #4

- plugins/modules/aci_interface_policy_port_security.py
- tests/integration/targets/aci_interface_policy_port_security/aliases
- tests/integration/targets/aci_interface_policy_port_security/tasks/main.yml
Addition of attribute: timeout
Addition of test file
> [aci_interface_policy_port_security]addition of attribute:timeout fixes #19

- plugins/modules/aci_interface_policy_leaf_breakout_port_group.py
- tests/integration/targets/aci_interface_policy_leaf_breakout_port_group/aliases
- tests/integration/targets/aci_interface_policy_leaf_breakout_port_group/tasks/main.yml
-build a new module to create leaf breakout port group
-small test file for this module
resolve #18
> [aci_interface_policy_leaf_breakout_port_group] Add breakout cable support

- plugins/module_utils/aci.py
- plugins/modules/aci_cloud_provider.py
- plugins/modules/aci_cloud_region.py
- plugins/modules/aci_cloud_zone.py
- plugins/modules/aci_epg_to_contract_master.py
- plugins/modules/aci_fabric_scheduler.py
- plugins/modules/aci_firmware_group_node.py
- plugins/modules/aci_rest.py
- plugins/modules/aci_system.py
- tests/integration/inventory.networking
Fix import warnings from last release
Fix IP of one APIC in integration test inventory
> Fix import warnings

- plugins/doc_fragments/aci.py
- plugins/module_utils/aci.py
Add Ansible Network ENV to fallback
> Add Ansible Network ENV to fallback

- plugins/modules/aci_ap.py
- plugins/modules/aci_epg.py
- tests/integration/targets/aci_ap/tasks/main.yml
- tests/integration/targets/aci_epg/tasks/main.yml
Updated aci_ap and aci_epg modules with attribute monitoring policy
Updated respective test files
> Ability to add monitoring policy to epgs and anps fixes #67

- plugins/module_utils/aci.py
- plugins/modules/aci_firmware_group.py
Fixes unused variables in aci.py
> Fix warning from latest galaxy release. fixes #100

- plugins/module_utils/aci.py
- tests/integration/targets/aci_aaa_user_certificate/tasks/main.yml
Made changes to support cryptography for sigining, (as pyOpenSSL will be deprecated eventually). Solves issue #13
> [aci] Added functionality to support cryptography for signing fixes #13

- .github/workflows/ansible-test.yml
- plugins/modules/aci_cloud_subnet.py
- plugins/modules/aci_fabric_scheduler.py
Upgraded CI with latest version of python and ansible
> Ci workflow

- plugins/modules/aci_aep_to_epg.py
- tests/integration/targets/aci_aep_to_epg/aliases
- tests/integration/targets/aci_aep_to_epg/tasks/main.yml
[Issue 103](https://github.com/CiscoDevNet/ansible-aci/issues/103): new module added
> aci_aep_to_epg

- tests/integration/inventory.networking
- tests/integration/targets/aci_cloud_cidr/tasks/main.yml
- tests/integration/targets/aci_cloud_ctx_profile/tasks/main.yml
- tests/integration/targets/aci_cloud_provider/tasks/main.yml
- tests/integration/targets/aci_cloud_region/tasks/main.yml
- tests/integration/targets/aci_cloud_subnet/tasks/main.yml
- tests/integration/targets/aci_cloud_vpn_gateway/tasks/main.yml
- tests/integration/targets/aci_cloud_zone/tasks/main.yml
- tests/integration/targets/aci_domain/tasks/vmm-vmware.yml
- tests/integration/targets/aci_domain_to_encap_pool/tasks/main.yml
- tests/integration/targets/aci_epg_to_domain/tasks/main.yml
- tests/integration/targets/aci_filter_entry/tasks/main.yml
- tests/integration/targets/aci_firmware_source/tasks/main.yml
- tests/integration/targets/aci_vmm_credential/tasks/vmware.yml
Changes to cloud module to execute only cloud sites from inventory
> [ACI test case fixes] Changes made in inventory.networking

- plugins/modules/aci_l3out_logical_interface_profile.py
- tests/integration/targets/aci_l3out_logical_interface_profile/aliases
- tests/integration/targets/aci_l3out_logical_interface_profile/tasks/main.yml
New module to manage L3out interface profiles
> L3Out Interface Profile

- plugins/modules/aci_contract_export.py
- plugins/modules/aci_vzany_to_contract.py
- tests/integration/targets/aci_contract_export/aliases
- tests/integration/targets/aci_contract_export/tasks/main.yml
- tests/integration/targets/aci_vzany_to_contract/aliases
- tests/integration/targets/aci_vzany_to_contract/tasks/main.yml
new modules:
- aci_contract_export.py - Export a contract to another tenant
- aci_vzany_to_contract - Bind provider/consumer contracts and contract interfaces to vzAny
> contract_enhancements

- plugins/modules/aci_bd.py
- tests/integration/targets/aci_bd/tasks/main.yml
I have added ipv6_l3_unknown_multicast parameter to be able to configure it on Bridge Domain.
Added into test section as well.
> added ipv6_l3_unknown_multicast to aci_bd

- plugins/modules/aci_epg.py
- tests/integration/targets/aci_epg/tasks/main.yml
I have added custom_qos_policy parameter to be able to configure it on Endpoint Group.
Added into test section as well.
> added custom_qos_policy to aci_epg

- .github/workflows/ansible-test.yml
- plugins/modules/aci_static_binding_to_epg.py
Made changes with respect to galaxy importer similar to MSO
> CI/CD  galaxy importer and coverage changes.

- plugins/modules/aci_interface_blacklist.py
- tests/integration/targets/aci_interface_blacklist/tasks/main.yml
I found a bug in my code while writing the description code.  ACI accepted the code in the model but physically it was not changing, since "eth" was defined in wrong place of the string. 
Manually verified the changes to real ACI fabric, and adjusted the automated test cases accordingly.
> Interface blacklist bug fix

- plugins/modules/aci_static_binding_to_epg.py
- tests/integration/targets/aci_static_binding_to_epg/tasks/main.yml
interface_types "fex_port_channel" and "fex_vpc" added
> Interface types added for Po's and vPC's using fex-ports

- plugins/modules/aci_cloud_ap.py
- tests/integration/targets/aci_cloud_ap/aliases
- tests/integration/targets/aci_cloud_ap/tasks/main.yml
- add aci_cloud_ap
- add test file for aci_cloud_ap
> Add module aci cloud ap

- plugins/modules/aci_cloud_epg.py
- tests/integration/targets/aci_cloud_epg/aliases
- tests/integration/targets/aci_cloud_epg/tasks/main.yml
- Create module aci_cloud_epg
- Add test file for aci_cloud_epg
#2
> [aci_cloud_epg] Add module aci_cloud_epg & test file

- plugins/modules/aci_cloud_bgp_asn.py
- tests/integration/targets/aci_cloud_bgp_asn/aliases
- tests/integration/targets/aci_cloud_bgp_asn/tasks/main.yml
> Added test cases to cloud BGP ASN module

- plugins/modules/aci_cloud_epg.py
- plugins/modules/aci_cloud_external_epg.py
- plugins/modules/aci_cloud_external_epg_selector.py
- tests/integration/targets/aci_cloud_ap/tasks/main.yml
- tests/integration/targets/aci_cloud_external_epg/aliases
- tests/integration/targets/aci_cloud_external_epg/tasks/main.yml
- tests/integration/targets/aci_cloud_external_epg_selector/aliases
- tests/integration/targets/aci_cloud_external_epg_selector/tasks/main.yml
> [aci_cloud_external_epg] Added test cases for cloud external epg. issue #2

- plugins/module_utils/aci.py
- plugins/modules/aci_cloud_epg_selector.py
- tests/integration/targets/aci_cloud_epg_selector/aliases
- tests/integration/targets/aci_cloud_epg_selector/tasks/main.yml
- Add module aci_cloud_epg_selector
- Add test file for aci_cloud_epg_selector
> [aci_cloud_epg_selector] Add module for cloud epg selector

- plugins/modules/aci_interface_description.py
- tests/integration/targets/aci_interface_description/aliases
- tests/integration/targets/aci_interface_description/tasks/main.yml
Addresses issue #165.
@lhercot I do a aci.query call to get the node type. Not sure whether this is desirable or whether you prefer input variables for this? Let me know I can change accordingly.
> Feature Set Interface Description

- plugins/modules/aci_fabric_spine_profile.py
- plugins/modules/aci_fabric_spine_switch_assoc.py
- plugins/modules/aci_fabric_switch_block.py
- tests/integration/targets/aci_fabric_spine_profile/aliases
- tests/integration/targets/aci_fabric_spine_profile/tasks/main.yml
- tests/integration/targets/aci_fabric_spine_switch_assoc/aliases
- tests/integration/targets/aci_fabric_spine_switch_assoc/tasks/main.yml
- tests/integration/targets/aci_fabric_switch_block/aliases
- tests/integration/targets/aci_fabric_switch_block/tasks/main.yml
This PR adds modules and integration tests for fabric spine switch profiles. The modules allow configuration of the following classes:
- fabricSpineP
- fabricSpineS
- fabricRsSpNodePGrp
- fabricNodeBlk
> Fabric spine profiles

- plugins/modules/aci_epg_to_contract.py
- plugins/modules/aci_epg_to_contract_interface.py
- tests/integration/targets/aci_epg_to_contract_interface/aliases
- tests/integration/targets/aci_epg_to_contract_interface/tasks/main.yml
Note:
Added a new module to create Consumed Contract Interface between two tenants.
> Inter-Tenant Consumed Contract Interface between two tenants

- plugins/modules/aci_epg_to_contract.py
- tests/integration/targets/aci_l3out_static_routes/tasks/main.yml
Note:
Changed tenant name on Query all relationships task
Added verifications to validate the task changes
> Added verifications to aci_l3out_static_routes

- plugins/module_utils/aci.py
- plugins/modules/aci_tenant_span_dst_group.py
- tests/integration/targets/aci_l3out_static_routes/tasks/main.yml
- tests/integration/targets/aci_tenant_span_dst_group/aliases
- tests/integration/targets/aci_tenant_span_dst_group/tasks/main.yml
aci.py-
Modified to accommodate idempotency for child within child when used in the same module.
Modified aci_tenant_span_dst_group and created test file.
> Modify [aci_tenant_span_dst_group] and aci library

- plugins/module_utils/aci.py
- tests/integration/targets/aci_tenant/tasks/main.yml
Note:
Added logic to store mo object config if the task has made changes on server side
Added verifications to validate output file content using output_path parameter
> Added logic to store mo object config on output file

- plugins/modules/aci_domain.py
- plugins/modules/aci_vmm_uplink.py
- plugins/modules/aci_vmm_uplink_container.py
- tests/integration/targets/aci_domain/tasks/fc.yml
- tests/integration/targets/aci_domain/tasks/vmm-vmware.yml
- tests/integration/targets/aci_vmm_uplink/aliases
- tests/integration/targets/aci_vmm_uplink/tasks/main.yml
- tests/integration/targets/aci_vmm_uplink_container/aliases
- tests/integration/targets/aci_vmm_uplink_container/tasks/main.yml
This PR updates the aci_domain module to add support for the accessMode and enableVmFolder attributes for VMM domains, and adds modules and integration tests for the vmmUplinkPCont and vmmUplinkP objects for VMWare domains.
> VMWare updates

- plugins/modules/aci_epg.py
- tests/integration/targets/aci_epg/tasks/main.yml
Note:
Added uSeg parameter to create micro-segmented EPGs and updated test cases for uSeg EPGs.
> Added useg parameter to create microsegmented EPGs

- plugins/modules/aci_interface_description.py
- tests/integration/targets/aci_interface_description/tasks/main.yml
Note:
Added tasks to validate interfaces query result and updated aci_interface_description module.
> Added tasks to validate interfaces query result and updated module file

- plugins/modules/aci_epg.py
> fixed typo

- plugins/modules/aci_bulk_static_binding_to_epg.py
- tests/integration/targets/aci_bulk_static_binding_to_epg/aliases
- tests/integration/targets/aci_bulk_static_binding_to_epg/tasks/main.yml
Note:
Created a module to bind multiple interfaces in one go and added test cases.
> Added Logic to bind multiple interfaces in one go

- plugins/modules/aci_epg_to_domain.py
- tests/integration/targets/aci_epg_to_domain/tasks/main.yml
> [minor_change] Added active/stanby vmm uplinks for epg to domain

- plugins/modules/aci_aep_to_epg.py
- tests/integration/targets/aci_aep_to_epg/tasks/main.yml
> fix issue #262

- .github/workflows/ansible-test.yml
- plugins/modules/aci_l3out_static_routes.py
- plugins/modules/aci_rest.py
- plugins/modules/aci_vmm_uplink_container.py
Note:
Added Ansible Core version 2.13.0 to the Github workflows ansible-test.yml file and fixed a few module documentations.
> Fixed ansible-core-2.13.0 sanity failure

- plugins/modules/aci_epg_to_domain.py
- tests/integration/targets/aci_epg_to_domain/tasks/main.yml
> [minor_change] adding missing options aci epg to domain

- plugins/modules/aci_rest.py
- tests/integration/network-integration.requirements.txt
- tests/integration/targets/aci_rest/tasks/json_string.yml
- tests/integration/targets/aci_rest/tasks/main.yml
- tests/integration/targets/aci_rest/tasks/xml_file.yml
- tests/integration/targets/aci_rest/tasks/xml_files/tn-ans_test_create.xml
- tests/integration/targets/aci_rest/tasks/xml_files/tn-ans_test_delete.xml
- tests/integration/targets/aci_rest/tasks/xml_files/tn-ans_test_negative_update_check.xml
- tests/integration/targets/aci_rest/tasks/xml_files/tn-ans_test_update.xml
Note:
Removed unwanted code from the aci_rest module and add xml file validation tasks.
> Added xml file validation to the aci_rest module

- plugins/modules/aci_interface_selector_to_switch_policy_leaf_profile.py
- tests/integration/targets/aci_interface_selector_to_switch_policy_leaf_profile/tasks/main.yml
> Fix issue 317

- plugins/modules/aci_aaa_user_domain.py
- plugins/modules/aci_aaa_user_role.py
- tests/integration/targets/aci_aaa_user_domain/tasks/main.yml
- tests/integration/targets/aci_aaa_user_role/tasks/main.yml
Note:
Added **aci_aaa_user_domain** and **aci_aaa_user_role** modules to assign roles and permissions to a user.
> Added modules to assign roles and permissions to a user

- plugins/modules/aci_rest.py
> [minor change] aci rest parameter updates

- plugins/modules/aci_encap_pool_range.py
- tests/integration/targets/aci_encap_pool_range/tasks/vlan.yml
fixes #345, sanity will fail committed fix to this in PR #367.
> [minor_change] range name not required

- plugins/modules/aci_interface_blacklist.py
- plugins/modules/aci_l3out_bgp_peer.py
- tests/integration/targets/aci_interface_blacklist/tasks/main.yml
> 351 query all bugfix

- plugins/module_utils/aci.py
- plugins/module_utils/constants.py
- plugins/modules/aci_access_span_dst_group.py
- plugins/modules/aci_access_span_filter_group.py
- plugins/modules/aci_access_span_filter_group_entry.py
- plugins/modules/aci_access_span_src_group.py
- plugins/modules/aci_access_span_src_group_src.py
- plugins/modules/aci_access_span_src_group_src_path.py
- plugins/modules/aci_tenant_span_dst_group.py
- plugins/modules/aci_tenant_span_src_group_src.py
- tests/integration/targets/aci_access_span_src_group/aliases
- tests/integration/targets/aci_access_span_src_group/tasks/main.yml
- tests/integration/targets/aci_access_span_src_group_src/aliases
- tests/integration/targets/aci_access_span_src_group_src/tasks/main.yml
- tests/integration/targets/aci_access_span_src_group_src_path/aliases
- tests/integration/targets/aci_access_span_src_group_src_path/tasks/main.yml
> 391 access span src group

- plugins/modules/aci_fabric_interface_policy_group.py
- tests/integration/targets/aci_fabric_interface_policy_group/aliases
- tests/integration/targets/aci_fabric_interface_policy_group/tasks/main.yml
Note:
Created a module to manage Leaf and Spine fabric interface policy groups.
> Added Fabric Interface Policy Groups module

- plugins/module_utils/aci.py
- plugins/module_utils/constants.py
- plugins/modules/aci_access_switch_policy_group.py
- tests/integration/inventory.networking
- tests/integration/targets/aci_access_switch_policy_group/aliases
- tests/integration/targets/aci_access_switch_policy_group/tasks/main.yml
This is a single module (aci_access_switch_policy_group) from a larger PR of tim cragg https://github.com/CiscoDevNet/ansible-aci/pull/419
Splitting up the module for easier review
> Tim cragg access switch policy group

- plugins/modules/aci_l3out.py
- tests/integration/targets/aci_l3out/tasks/main.yml
aci_l3out part of the #125 issue
> [minor_change] add support for sr-mpls in aci_l3out module

- plugins/module_utils/constants.py
- plugins/modules/aci_interface_policy_eigrp.py
- plugins/modules/aci_key_policy.py
- plugins/modules/aci_keychain_policy.py
- plugins/modules/aci_l3out_eigrp_interface_profile.py
- tests/integration/targets/aci_interface_policy_eigrp/aliases
- tests/integration/targets/aci_interface_policy_eigrp/tasks/main.yml
- tests/integration/targets/aci_key_policy/aliases
- tests/integration/targets/aci_key_policy/tasks/main.yml
- tests/integration/targets/aci_keychain_policy/aliases
- tests/integration/targets/aci_keychain_policy/tasks/main.yml
- tests/integration/targets/aci_l3out_eigrp_interface_profile/aliases
- tests/integration/targets/aci_l3out_eigrp_interface_profile/tasks/main.yml
Classes added as new Modules:
- eigrpIfP (L3out EIGRP Interface Profile)
- eigrpIfPol (EIGRP Interface Policy)
- fvKeyChainPol (Keychain Policy)
- fvKeyPol (Key Policy)
> Add EIGRP policy configurations for L3Out Logical Interface Profile.

- plugins/modules/aci_l3out_interface.py
- tests/integration/targets/aci_l3out_interface/tasks/main.yml
fixes #536 
aci_l3out_interface part of the #125
This PR is depending on #542  and should be merged after. Cherry pick the commit in case you want to run tests.
> 125 aci l3out interface

- plugins/modules/aci_vmm_controller.py
- tests/integration/targets/aci_vmm_controller/tasks/main.yml
> [bugfix] fix query in aci_vmm_controller

- plugins/module_utils/constants.py
- plugins/modules/aci_qos_custom_policy.py
- plugins/modules/aci_qos_dot1p_class.py
- plugins/modules/aci_qos_dscp_class.py
- tests/integration/targets/aci_qos_custom_policy/aliases
- tests/integration/targets/aci_qos_custom_policy/tasks/main.yml
- tests/integration/targets/aci_qos_dot1p_class/aliases
- tests/integration/targets/aci_qos_dot1p_class/tasks/main.yml
- tests/integration/targets/aci_qos_dscp_class/aliases
- tests/integration/targets/aci_qos_dscp_class/tasks/main.yml
Added class objects as new modules:
- qosCustomPol
- qosDscpClass
- qosDot1PClass
is part of issue #126
> Add QoS Custom Policy and its child classes as new modules

- plugins/modules/aci_bd.py
- plugins/modules/aci_igmp_interface_policy.py
- tests/integration/targets/aci_bd/tasks/main.yml
> [minor_change] Added relevant missing options to the bd module.

- plugins/modules/aci_cloud_subnet.py
- tests/integration/inventory.networking
- tests/integration/targets/aci_cloud_subnet/tasks/main.yml
> [minor_change] Added support for configuring Azure cloud subnets using the aci_cloud_subnet module.

- plugins/module_utils/aci.py
- plugins/module_utils/constants.py
- plugins/modules/aci_interface_policy_storm_control.py
- tests/integration/targets/aci_interface_policy_storm_control/aliases
- tests/integration/targets/aci_interface_policy_storm_control/tasks/main.yml
Update and Polish the Storm Control Interface Policy module and integration test first created by @netgirard.
From Pull request #389 
Updated Module:
- aci_interface_policy_storm_control (class:stormctrlIfPol)
> Update Storm Control Policy Module and integration test

- docs/optimizing.md
Adjusted the expected performance improvement when using HTTPAPI and suppress options.
> Reword suppress option documentation

- plugins/modules/aci_aaa_key_ring.py
- plugins/modules/aci_aaa_user.py
- plugins/modules/aci_cloud_aws_provider.py
- plugins/modules/aci_cloud_vpn_gateway.py
- plugins/modules/aci_esg_epg_selector.py
- plugins/modules/aci_fabric_external_connection_profile.py
- plugins/modules/aci_file_remote_path.py
- plugins/modules/aci_firmware_source.py
- plugins/modules/aci_l3out_bfd_interface_profile.py
- plugins/modules/aci_l3out_bfd_multihop_interface_profile.py
- plugins/modules/aci_l3out_extepg.py
- plugins/modules/aci_l3out_static_routes.py
- plugins/modules/aci_match_rule.py
- plugins/modules/aci_route_control_context.py
- plugins/modules/aci_route_control_profile.py
- plugins/modules/aci_snmp_user.py
- plugins/modules/aci_switch_leaf_selector.py
- plugins/modules/aci_vmm_credential.py
- plugins/modules/aci_vrf_leak_internal_subnet.py
- tests/integration/targets/aci_aaa_key_ring/tasks/main.yml
- tests/integration/targets/aci_aaa_user/tasks/main.yml
- tests/integration/targets/aci_file_remote_path/tasks/main.yml
- tests/integration/targets/aci_firmware_source/tasks/main.yml
- tests/integration/targets/aci_key_policy/tasks/main.yml
- tests/integration/targets/aci_l3out_bgp_peer/tasks/main.yml
- tests/integration/targets/aci_l3out_logical_interface_profile_ospf_policy/tasks/main.yml
- tests/integration/targets/aci_snmp_user/tasks/main.yml
- tests/integration/targets/aci_system_global_aes_passphrase_encryption/tasks/main.yml
These properties will not be returned by APIC on a GET request.
- Fixed some class name typos
- Checked module classes including any child classes.
Fixes #648
> [minor_change] Added missing warnings to any secure options

- plugins/httpapi/aci.py
- plugins/module_utils/aci.py
- tests/integration/targets/aci_tenant/tasks/httpapi_connection.yml
> [minor_change] Enable relative path and/or filename of private key in playbook for httpapi plugin.

- plugins/modules/aci_ntp_policy.py
- tests/integration/targets/aci_ntp_policy/tasks/main.yml
> [minor_change] Add stratum attribute to aci_ntp_policy module (DCNE-54)

- plugins/modules/aci_esg_ip_subnet_selector.py
> [bugfix] Fix examples in aci_esg_ip_subnet_selector module (DCNE-306)

- plugins/modules/aci_interface_config.py
- tests/integration/targets/aci_interface_config/tasks/main.yml
> 730 doc enhancement pc member (DCNE-309)

- plugins/modules/aci_bd_subnet.py
- tests/integration/targets/aci_bd_subnet/tasks/main.yml
> [bugfix] Fix type of subnet_control in aci_bd_subnet from string to list of strings (DCNE-335)

- plugins/modules/aci_config_snapshot.py
- tests/integration/targets/aci_config_snapshot/tasks/main.yml
> 775 failing aci snapshot (DCNE-449)
