plugins/modules/aci_cloud_zone.py, tests/integration/targets/aci_cloud_zone/aliases, tests/integration/targets/aci_cloud_zone/tasks/main.yml
- complete the 'aci_cloud_zone' module which is used to query cloud availability zone under the cloud region
- build test file for this query module
- tested in aws cloud apic (Version 5.0(2e))
=> aci_cloud_zone module

plugins/modules/aci_rest.py
Update:
- If you don’t have any attributes, it may be necessary to add: attributes: {} as the APIC does expect the entry to precede any children.
=> Updated documentation fixes #30

plugins/modules/aci_l3out_extsubnet.py, tests/integration/targets/aci_l3out_extsubnet/aliases, tests/integration/targets/aci_l3out_extsubnet/tasks/main.yml
make 'scope' attribute default as 'import-security' to avoid crash
resolve #70
=> [aci_l3out_extsubnet] fix issue of scope attribute not being specified

plugins/modules/aci_domain_to_encap_pool.py
According to documentation, the valid options for domain_type are fc, l2dom, l3dom, phys, and vmm. However, when building the full URL, l2ext and l3ext are compared against instead of l2dom and l3dom. This causes the error "UnboundLocalError: local variable 'domain_class' referenced before assignment" when trying to reference those domain types.
=> fix incorrect domain types

plugins/module_utils/aci.py
get_nested_config was always returning True if there was a matching child class, even if none of the attributes matched.
=> existing_config variable is not reset during loop

plugins/modules/aci_epg_to_domain.py
PR #79 caused an issue for me, where this new child class was always added to the ACI config, when it is only required for VMM domains.
This PR makes the child config configurable per-domain type.
=> move child config and classes to per-domain-type

plugins/modules/aci_aaa_user_certificate.py, tests/integration/network-integration.requirements.txt, tests/integration/targets/aci_aaa_user_certificate/tasks/main.yml
There was discrepancy with certificate_name as it was defined twice:
1. For username
2. For certificate's name
Fixed the issue by changing attribute name 'certificate_name' to name in the module.
=> Changed certificate_name to name for Query operations. fixes #101

plugins/modules/aci_bd.py, tests/integration/targets/aci_bd/tasks/main.yml
I have added route_profile and route_profile_l3_out parameters to be able to configure both on Bridge Domain.
It was already available in aci_bd_subnet for Bridge Domain Subnet object.
=> added route_profile, route_profile_l3_out to aci_bd

plugins/module_utils/aci.py, plugins/modules/aci_l3out_logical_interface_vpc_member.py, plugins/modules/aci_l3out_static_routes.py, plugins/modules/aci_l3out_static_routes_nexthop.py
This changes insert URI path separator '/' in path attribute that fix errors like this:
```
TASK [aci_l2out_logical_interface_path] 
fatal: [apic]: FAILED! => changed=false
error:
code: '102'
text: 'configured object ((Dn0)) not found Dn0=uni/tn-Tn1/l2out-BD113_i9/lnodep-default/lifp-defaultrspathL2OutAtt-[topology/pod-2/protpaths-301-302/pathep-[L2o2_i9]]/r
spathL2OutAtt-[topology/pod-2/protpaths-301-302/pathep-[L2o2_i9]], '
...
```
Note joined `lnodep-<name>` and `rspathL2OutAtt-<path>` entries.
Related:
- issue: #11
- wrong commit that is fixed: anvitha-jain@a2f8af4df984761f9b689668f10580741fa7170a
=> Fix missed separators '/' in path attribute of ACIModule class.

plugins/modules/aci_l2out_extepg_to_contract.py, tests/integration/targets/aci_l2out_extepg_to_contract/aliases, tests/integration/targets/aci_l2out_extepg_to_contract/tasks/main.yml
This commit add new module module aci_l2out_extepg_to_contract that closely resembles and is based on aci_l3out_extepg_to_contract.
=> Add new module aci_l2out_extepg_to_contract

plugins/module_utils/aci.py, plugins/modules/aci_vmm_vswitch.py, plugins/modules/aci_vmm_vswitch_policy.py, tests/integration/targets/aci_vmm_vswitch_policy/aliases, tests/integration/targets/aci_vmm_vswitch_policy/tasks/main.yml
This module adds support for vswitch policies on VMM domains including enhanced LAG for VMWare. It addresses another part of the functionality needed for #29 
I'm not sure if we should keep all possible `vm_providers`, as per ACI UI I could only test the creation of vswitch policy for Microsoft SCVMM and VMWare  domains. Otherwise I'm also happy to remove the other `vm_providers` and eventually only add them back if we are sure the capabilites exist.
=> add module aci_vmm_vswitch

plugins/modules/aci_domain.py, tests/integration/targets/aci_domain/tasks/fc.yml, tests/integration/targets/aci_domain/tasks/l2dom.yml, tests/integration/targets/aci_domain/tasks/l3dom.yml, tests/integration/targets/aci_domain/tasks/phys.yml, tests/integration/targets/aci_domain/tasks/vmm-vmware.yml
This change partially addresses #29 adding support for  infrastructure port groups and tag collection on the vmm Domain.
I would plan to address the controller part via a new module named "aci_vmm_controller_to_domain"  working similar like  the existing "aci_vmm_credential"
=> aci_domain add support for vmm domain  infra port group and tag collection

plugins/modules/aci_rest.py
Addresses issue https://github.com/CiscoDevNet/ansible-aci/issues/162
Skip output_file when "Method: Get" is used
Change to generate file when "Method: Post/Delete".
Requesting by xml is not supported.
=> Fixed the behavior when output is specified in aci_rest.

plugins/modules/aci_vlan_pool_encap_block.py, tests/integration/targets/aci_vlan_pool_encap_block/tasks/main.yml
Removed block_name from the required parameter list and added pool_allocation_mode to the required parameter list.
Deleted pool_allocation_mode - **Missing required param - error message works** test case because it is invalid check for the current code.
=> aci_vlan_pool_encap_block - Removed block_name from the required parameter list

plugins/modules/aci_l3out_interface.py, plugins/modules/aci_l3out_interface_secondary_ip.py, plugins/modules/aci_l3out_logical_interface_vpc_member.py, tests/integration/targets/aci_l3out_interface/tasks/main.yml, tests/integration/targets/aci_l3out_interface_secondary_ip/aliases, tests/integration/targets/aci_l3out_interface_secondary_ip/tasks/main.yml, tests/integration/targets/aci_l3out_logical_interface_vpc_member/tasks/main.yml
- added ipv6Dad attribute
- renamed arguments for node and interface profiles (inline with the other l3out modules)
- added arguments to describe fabricPathEp with pod_id, node_id, path_ep (inline with aci_l3out_interface module)
- added addr attribute
- added ipv6Dad attribute
- new module to manage l3out interface secondary IP addresses (l3ext:Ip)
=> L3out interface enhancements

plugins/modules/aci_access_port_to_interface_policy_leaf_profile.py, tests/integration/targets/aci_access_port_to_interface_policy_leaf_profile/tasks/main.yml
Note:
Added fex_port_channel, fex_vpc interface types access_port_to_interface_policy_leaf_profile module and updated testcases.
=> Added fex_port_channel and fex_vpc interface types access_port_to_interface_policy_leaf_profile

plugins/modules/aci_bd.py, plugins/modules/aci_bd_to_l3out.py, plugins/modules/aci_epg_monitoring_policy.py, plugins/modules/aci_filter_entry.py, plugins/modules/aci_firmware_group.py, plugins/modules/aci_firmware_group_node.py, plugins/modules/aci_interface_policy_fc.py, plugins/modules/aci_interface_policy_l2.py, plugins/modules/aci_interface_policy_link_level.py, plugins/modules/aci_interface_policy_lldp.py, plugins/modules/aci_interface_policy_mcp.py, plugins/modules/aci_interface_policy_port_channel.py, plugins/modules/aci_interface_policy_port_security.py, plugins/modules/aci_l2out_logical_interface_path.py, plugins/modules/aci_l2out_logical_interface_profile.py, plugins/modules/aci_l2out_logical_node_profile.py, plugins/modules/aci_l3out_extepg.py, plugins/modules/aci_l3out_route_tag_policy.py, plugins/modules/aci_maintenance_group.py, plugins/modules/aci_maintenance_group_node.py, plugins/modules/aci_maintenance_policy.py, plugins/modules/aci_tenant_action_rule_profile.py, plugins/modules/aci_tenant_span_src_group.py, plugins/modules/aci_tenant_span_src_group_to_dst_group.py
fixes #299 
@lhercot these examples still miss proper examples, shall I work on these or separate issue?
plugins/modules/aci_bd_to_l3out.py
plugins/modules/aci_epg_monitoring_policy.py
plugins/modules/aci_filter_entry.py
plugins/modules/aci_firmware_group.py
plugins/modules/aci_firmware_group_node.py
plugins/modules/aci_interface_policy_fc.py
plugins/modules/aci_interface_policy_l2.py
plugins/modules/aci_interface_policy_lldp.py
plugins/modules/aci_interface_policy_mcp.py
plugins/modules/aci_interface_policy_port_channel.py
plugins/modules/aci_interface_policy_port_security.py
plugins/modules/aci_l2out_logical_interface_profile.py
plugins/modules/aci_l2out_logical_node_profile.py
plugins/modules/aci_l3out_route_tag_policy.py
plugins/modules/aci_maintenance_group.py …
=> [ignore] example documentation fix

plugins/modules/aci_rest.py
currently the aci_rest module only returns a status code of -1. Small fix to update the status with the correct response code
=> return correct http status code in aci_rest module

plugins/modules/aci_aaa_custom_privilege.py, plugins/modules/aci_aaa_domain.py, plugins/modules/aci_aaa_role.py, tests/integration/targets/aci_aaa_custom_privilege/aliases, tests/integration/targets/aci_aaa_custom_privilege/tasks/main.yml, tests/integration/targets/aci_aaa_domain/aliases, tests/integration/targets/aci_aaa_domain/tasks/main.yml, tests/integration/targets/aci_aaa_role/aliases, tests/integration/targets/aci_aaa_role/tasks/main.yml
Note:
Added modules to create and update AAA Domains, Roles and Custom Privileges on Cisco ACI fabrics.
=> Added aaa_domain, aaa_role and custom_privilege modules and test files

plugins/module_utils/aci.py, plugins/modules/aci_contract_subject.py, plugins/modules/aci_contract_subject_to_filter.py, tests/integration/targets/aci_contract_subject/tasks/main.yml, tests/integration/targets/aci_contract_subject_to_filter/tasks/main.yml
fixes #303 
discussion still needed for completion on the following topics:
- api accepts all direction types, but GUI checkmark on subject does not
- when combined all directions do show in GUI 
- when choice is made for "both" or a "combination of provider2consumer / consumer2provider" an additional api call will be required or restructure of code
- direction not saved as part of object config of subject, which is also not something that can be requested. check would then be needed on the children objects of subject.
- filter_existing in exit_json() used to manipulate the current/previous output. done in aci.py because another get_existing() is done for current status there. if done in aci_contract_subject_to_filter.py manipulation of current status was not possible when aci.exit_json() …
=> [minor_change] contract subject filter direction support

plugins/modules/aci_access_port_to_interface_policy_leaf_profile.py, plugins/modules/aci_interface_policy_leaf_profile_fex_policy_group.py, tests/integration/targets/aci_access_port_to_interface_policy_leaf_profile/tasks/main.yml, tests/integration/targets/aci_interface_policy_leaf_profile_fex_policy_group/aliases, tests/integration/targets/aci_interface_policy_leaf_profile_fex_policy_group/tasks/main.yml
Note:
Created a new module to add Fex Policy Groups and test case files.
Updated Interface Access Port Selector module.
=> Added Fex Profile Policy Group module

plugins/modules/aci_tenant_span_src_group_src.py, tests/integration/targets/aci_tenant_span_src_group/aliases, tests/integration/targets/aci_tenant_span_src_group/tasks/main.yml, tests/integration/targets/aci_tenant_span_src_group_src/aliases, tests/integration/targets/aci_tenant_span_src_group_src/tasks/main.yml, tests/integration/targets/aci_tenant_span_src_group_to_dst_group/aliases, tests/integration/targets/aci_tenant_span_src_group_to_dst_group/tasks/main.yml
=> [minor_change] source span sources support

plugins/module_utils/aci.py, plugins/modules/aci_l3out_bgp_peer.py, tests/integration/targets/aci_l3out_bgp_peer/tasks/main.yml
Note:
Added BGP Peer to the Node Profile level and also added the functionality to bind Route Control Profile to BGP Peer.
=> Added Node Profile BGP Peer and Route Control Profile functionalities

plugins/modules/aci_static_node_mgmt_address.py
=> [ignore] Fix aci_static_node_mgmt_address example using wrong type attribute

plugins/modules/aci_bd_subnet.py, plugins/modules/aci_vrf.py, tests/integration/targets/aci_bd_subnet/tasks/main.yml, tests/integration/targets/aci_vrf/tasks/main.yml
Note:
Added IP Dataplane attribute to the aci_bd_subnet and aci_vrf module
=> Added IP Dataplane attribute to the subnet and vrf module

plugins/modules/aci_l3out_bgp_peer.py, tests/integration/targets/aci_l3out_bgp_peer/tasks/main.yml
Note:
Added bgpLocalAsnP child object to aci_l3out_bgp_peer module to configure the local Autonomous System Number and Configuration.
=> Added bgpLocalAsnP child object to aci_l3out_bgp_peer module

plugins/module_utils/constants.py, plugins/modules/aci_filter_entry.py, tests/integration/targets/aci_filter_entry/tasks/main.yml
Note:
Added the TCP session rules and match fragment to the aci_filter_entry module also included the Source Port of the TCP/UDP protocol.
=> Added the TCP session rules and match fragment to aci_filter_entry module

plugins/module_utils/aci.py, plugins/modules/aci_rest.py, tests/integration/targets/aci_rest/tasks/error_handling.yml, tests/integration/targets/aci_rest/tasks/json_inline.yml, tests/integration/targets/aci_rest/tasks/json_string.yml, tests/integration/targets/aci_rest/tasks/xml_file.yml, tests/integration/targets/aci_rest/tasks/xml_string.yml, tests/integration/targets/aci_rest/tasks/yaml_inline.yml, tests/integration/targets/aci_rest/tasks/yaml_string.yml
=> [minor_change] add support for checkmode in aci_rest module

plugins/modules/aci_bgp_address_family_context_policy.py, plugins/modules/aci_bgp_best_path_policy.py, plugins/modules/aci_bgp_peer_prefix_policy.py, plugins/modules/aci_bgp_route_summarization_policy.py, plugins/modules/aci_bgp_timers_policy.py, tests/integration/targets/aci_bgp_address_family_context_policy/aliases, tests/integration/targets/aci_bgp_address_family_context_policy/tasks/main.yml, tests/integration/targets/aci_bgp_peer_prefix_policy/aliases, tests/integration/targets/aci_bgp_peer_prefix_policy/tasks/main.yml, tests/integration/targets/aci_bgp_route_summarization_policy/aliases, tests/integration/targets/aci_bgp_route_summarization_policy/tasks/main.yml
Add the following missing BGP policies:
- BGP Peer Prefix policy
- BGP Route Summarization policy
- BGP Address Family Context policy
=> [minor_change] Add extra missing BGP policies as new modules

plugins/modules/aci_dhcp_option.py, plugins/modules/aci_dhcp_option_policy.py, plugins/modules/aci_l3out_dhcp_relay_label.py, tests/integration/targets/aci_dhcp_option/aliases, tests/integration/targets/aci_dhcp_option/tasks/main.yml, tests/integration/targets/aci_dhcp_option_policy/aliases, tests/integration/targets/aci_dhcp_option_policy/tasks/main.yml, tests/integration/targets/aci_l3out_dhcp_relay_label/aliases, tests/integration/targets/aci_l3out_dhcp_relay_label/tasks/main.yml
=> Add DHCP Relay configurations for L3Out Logical Interface Profile.

plugins/modules/aci_interface_policy_link_level.py, tests/integration/targets/aci_interface_policy_link_level/tasks/main.yml
"auto" for the link level policy is missing from the choices in the ansible module. This adds the "auto" option to allow an auto negotiating interface speed to be configured on the APIC controller
=> Add auto to link level speed options

plugins/module_utils/aci.py, plugins/module_utils/constants.py, plugins/modules/aci_netflow_exporter_policy.py, plugins/modules/aci_netflow_monitor_policy.py, plugins/modules/aci_netflow_monitor_to_exporter.py, plugins/modules/aci_netflow_record_policy.py, tests/integration/targets/aci_netflow_exporter_policy/aliases, tests/integration/targets/aci_netflow_exporter_policy/tasks/main.yml, tests/integration/targets/aci_netflow_monitor_policy/aliases, tests/integration/targets/aci_netflow_monitor_policy/tasks/main.yml, tests/integration/targets/aci_netflow_monitor_to_exporter/aliases, tests/integration/targets/aci_netflow_monitor_to_exporter/tasks/main.yml, tests/integration/targets/aci_netflow_record_policy/aliases, tests/integration/targets/aci_netflow_record_policy/tasks/main.yml
- aci_netflow_monitor_policy (netflowMonitorPol)
- aci_netflow_record_policy (netflowRecordPol)
- aci_netflow_exporter_policy (netflowExporterPol)
is part of issue #126
=> Add Netflow Policies as new modules.

plugins/modules/aci_bd_rogue_exception_mac.py, plugins/modules/aci_bd_to_netflow_monitor_policy.py, tests/integration/targets/aci_bd_rogue_exception_mac/aliases, tests/integration/targets/aci_bd_rogue_exception_mac/tasks/main.yml, tests/integration/targets/aci_bd_to_l3out/tasks/main.yml, tests/integration/targets/aci_bd_to_netflow_monitor_policy/aliases, tests/integration/targets/aci_bd_to_netflow_monitor_policy/tasks/main.yml
1. Added modules and tests for 1-N   Relationships for BD.
- bd_to_netflow_monitor_policy
- bd_rogue_exception_mac
2. Added, missing clean-up  in bd_to_l3out tests.
3. Please note this PR is reliant on the merging of PR #582 
Closes #534
=> [minor change] Added modules and tests for missing 1-N children for BD.

plugins/module_utils/aci.py, plugins/modules/aci_l3out_logical_interface_profile.py, tests/integration/targets/aci_l3out_logical_interface_profile/tasks/main.yml
=> Add new Interface Protocols to configure for aci_l3out_logical_interface_profile.

.github/workflows/ansible-test.yml
I had to pin to this version because the latest versions (0.4.21) released last week prints out quite a few unrelated warnings and fails the CI.
This is a temporary fix. The full fix should be completed as part of #639
=> [ignore] Pinned CI galaxy-importer version to 4.20

plugins/doc_fragments/aci.py, plugins/module_utils/aci.py, tests/integration/targets/aci_bd_subnet/tasks/main.yml, tests/integration/targets/aci_epg_to_contract/tasks/main.yml, tests/integration/targets/aci_l3out_static_routes/tasks/main.yml, tests/integration/targets/aci_static_binding_to_epg/tasks/main.yml
- If true, a look back GET will not be sent before a POST update to APIC.
- The previous state of the object will not be checked and the POST update will contain all configred properties.
- Additionally, added a fix to reduce GET calls when an object is unchanged.
=> [minor_change] Added Suppress Previous option to reduce the number of API calls.

README.md, docs/optimizing.md
- Added ACI HTTPAPI documentation
- Added suppress_previous and suppress_verification documentation
=> [minor_change] Added Playbook Optimizing documentation

plugins/modules/aci_l3out_logical_interface_vpc_member.py, tests/integration/targets/aci_l3out_logical_interface_vpc_member/tasks/main.yml
Minor bugfix - the l3extMember object uses side instead of name to build the DN, so the module should configure the side attribute instead of the name (I believe the name attribute is left as null if you build an l3extMember object through the APIC GUI).
Closes DCNE-93
=> fix: Correct vPC member side (DCNE-93)

plugins/module_utils/constants.py, plugins/modules/aci_dns_profile.py, tests/integration/targets/aci_dns_profile/tasks/main.yml
=> [minor_change] Add support for management epg configuration in aci_dns_profile module (DCNE-175)

plugins/modules/aci_domain_to_vlan_pool.py, tests/integration/targets/aci_domain_to_vlan_pool/tasks/main.yml
When state is absent, only the subclass for the domain should be deleted (infraRsVlanNs) not the whole domain config.
=> [bug_fix]: Add subclass to `aci_domain_to_vlan_pool` to fix deletion of binding (DCNE-207)

README.md
Readme should match this template https://access.redhat.com/articles/7068606
=> [bug_fix] Updated README to match RedHat's ansible collection template (DCNE-198)

plugins/modules/aci_epg_to_domain.py
=> [docs] Remove reference in documentation to encap_mode in the encap variable description of aci_epg_to_domain module (DCNE-225)

.github/workflows/ansible-test.yml, README.md, meta/runtime.yml, plugins/modules/aci_cloud_subnet.py, plugins/modules/aci_interface_description.py, plugins/modules/aci_interface_policy_hsrp.py, plugins/modules/aci_l2out_logical_interface_path.py, plugins/modules/aci_l2out_logical_interface_profile.py, plugins/modules/aci_l2out_logical_node_profile.py, plugins/modules/aci_l3out_bgp_peer.py, plugins/modules/aci_l3out_hsrp_group.py, plugins/modules/aci_l3out_hsrp_interface_profile.py, plugins/modules/aci_l3out_hsrp_secondary_vip.py, plugins/modules/aci_l3out_interface.py, plugins/modules/aci_l3out_interface_secondary_ip.py, plugins/modules/aci_l3out_logical_node.py, plugins/modules/aci_l3out_logical_node_profile.py, plugins/modules/aci_l3out_static_routes_nexthop.py
Fixes #706 
- Updated supported Python version to 3.11
- Fixed the additional sanity issues reported in Ansible Core 2.18
- Fixed the `seealso` FQCN references
=> [minor_change] Added support for Ansible 2.18 and dropped support for 2.15 (DCNE-247)

plugins/modules/aci_l3out_static_routes_nexthop.py, tests/integration/targets/aci_l3out_static_routes_nexthop/tasks/main.yml
This PR adds a new attribute, `preference`, to the `aci_l3out_static_routes_nexthop` module, enabling the configuration of a preference value for next-hop IP addresses in static routes. This change addresses a common use case where routing preferences need to be explicitly set for better control over routing decisions.
- Introduced the `preference` attribute to `aci_l3out_static_routes_nexthop`
- Added test cases for validating the new functionality
- The `preference` attribute is optional. If omitted, the API will use the default value of `0`.
- Ensured backward compatibility by not altering existing functionality without a `preference` value.
=> Add 'preference' attribute to aci_l3out_static_routes_nexthop (DCNE-303)

plugins/modules/aci_rest.py, tests/integration/targets/aci_rest/tasks/json_inline.yml, tests/integration/targets/aci_rest/tasks/json_string.yml, tests/integration/targets/aci_rest/tasks/xml_string.yml
This change adds  "page_size" and "page" optional paremeters to the aci_rest module in order to support pagination.
if the `page_size` parameter is set on a GET request, it controls the amount of objects to be returned on each page by the APIC response, then the `page` parameter controls which page is returned to the module. 
If the `page` parameter is not set, it returns the first page by default (0)
=> [minor_change] Add pagination support for aci_rest module (DCNE-101)

plugins/modules/aci_oob_contract.py, tests/integration/targets/aci_oob_contract/aliases, tests/integration/targets/aci_oob_contract/tasks/main.yml
added in module for oob_contract creation.
Updated test files for this as well.
=> [minor change] New module for out-of-band contract creation (DCNE-219)

.github/workflows/ansible-test.yml
=> [minor_change] Add support for Ansible Core 2.19 (DCNE-396)

plugins/modules/aci_l4l7_policy_based_redirect.py, plugins/modules/aci_l4l7_policy_based_redirect_destination.py, plugins/modules/aci_l4l7_redirect_health_group.py, tests/integration/targets/aci_l4l7_policy_based_redirect/aliases, tests/integration/targets/aci_l4l7_policy_based_redirect/tasks/main.yml, tests/integration/targets/aci_l4l7_policy_based_redirect_destination/aliases, tests/integration/targets/aci_l4l7_policy_based_redirect_destination/tasks/main.yml, tests/integration/targets/aci_l4l7_redirect_health_group/aliases, tests/integration/targets/aci_l4l7_redirect_health_group/tasks/main.yml
This PR contains completed aci_l4l7_policy_based_redirect and related modules from #186
=> Addition of aci_l4l7_policy_based_redirect and related modules (DCNE-391)
